rtx.restirGI.sampleStealingJitter = 3
rtx.fogColorScale = 0.08
rtx.bloom.burnIntensity = 0.5
rtx.restirGI.validateVisibilityChange = True
rtx.viewModel.scale = 0.25
rtx.capture.correctBakedTransforms = True
rtx.bloom.steps = 5
rtx.fallbackLightMode = 0
rtx.tonemap.exposureBias = 0
rtx.di.enableSpatialReuse = True
rtx.suppressLightKeeping = True
rtx.raytracedRenderTarget.enable = True
rtx.localtonemap.useAgX = True
rtx.skyMode = 0
rtx.restirGI.boilingFilterMinThreshold = 15
rtx.bloom.luminanceThreshold = 0
rtx.autoExposure.evMaxValue = 4
rtx.restirGI.useVirtualSample = False
rtx.di.maxHistoryLength = 1
rtx.autoExposure.evMinValue = -2
rtx.autoExposure.exposureCenterMeteringEnabled = True
rtx.tonemap.dynamicRange = 15
rtx.skyMinZThreshold = 0.999
rtx.di.enableDenoiserGradient = True
rtx.risLightSampleCount = 32
rtx.zUp = True
rtx.ignoreGameSpotLights = True
rtx.hideInstanceTextures = 0x02BE2A15C810EF35, 0x0B3B3EB9B097D24B, 0x260EAE29EC4727F3, 0x2A4919B8E007F4BD, 0x2BA80B56086F3627, 0x3FE4ECB3ED0BB942, 0x41C11B59983BC9E7, 0x4E6284007D1FB86F, 0x551F8376128C861F, 0x5A6AD182201BC20B, 0x5BCBA04A61BEA8FD, 0x630A078C1BDB715D, 0x6E13FE917F6AE35F, 0x7934A63FF4123CF2, 0x7B2A2AAEE36B085A, 0x7F78E4BDA3ADDF93, 0x9E70FB22B4F787C6, 0x9F874078BE0C83FF, 0xB5BB369B76D524FB, 0xB891791C783BC3B1, 0xBF45B3596CFE2E5C, 0xC8B5FA72B85EADC1, 0xCD03F36D3B022D28, 0xCECB7D0481A0D5CB, 0xD47CB0461D3FFA3D, 0xE791EACA53632BBB, 0xE7BFAD3513D56AB9, 0xEF4E20E2CCC643DC, 0xF492499FD6644B75
rtx.viewModel.enable = True
rtx.restirGI.useSampleStealing = 1
rtx.ignoreGameDirectionalLights = True
rtx.skyReprojectToMainCameraSpace = True
rtx.localtonemap.exposure = 0.6
rtx.skyReprojectScale = 17
rtx.useObsoleteHashOnTextureUpload = True
rtx.skyAutoDetect = 2   
rtx.lightConversionSphereLightFixedRadius = 9
rtx.ignoreGamePointLights = True
rtx.tonemappingMode = 1
rtx.localtonemap.finalizeWithACES = False
rtx.enableMultiStageTextureFactorBlending = True
